"""add_library_features_to_processed_transcripts

Revision ID: 391042c0cbc0
Revises: eeea4e4937d3
Create Date: 2025-08-02 01:33:13.852109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391042c0cbc0'
down_revision: Union[str, Sequence[str], None] = 'eeea4e4937d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_transcripts', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('processed_transcripts', sa.Column('video_title', sa.String(length=500), nullable=True))
    op.add_column('processed_transcripts', sa.Column('channel_name', sa.String(length=200), nullable=True))
    op.add_column('processed_transcripts', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('processed_transcripts', sa.Column('adapted_text', sa.Text(), nullable=True))
    op.add_column('processed_transcripts', sa.Column('adapted_word_count', sa.Integer(), nullable=True))
    op.add_column('processed_transcripts', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.add_column('processed_transcripts', sa.Column('added_by_username', sa.String(length=50), nullable=True))
    op.add_column('processed_transcripts', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('processed_transcripts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('processed_transcripts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'processed_transcripts', 'users', ['added_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processed_transcripts', type_='foreignkey')
    op.drop_column('processed_transcripts', 'updated_at')
    op.drop_column('processed_transcripts', 'is_active')
    op.drop_column('processed_transcripts', 'view_count')
    op.drop_column('processed_transcripts', 'added_by_username')
    op.drop_column('processed_transcripts', 'added_by_user_id')
    op.drop_column('processed_transcripts', 'adapted_word_count')
    op.drop_column('processed_transcripts', 'adapted_text')
    op.drop_column('processed_transcripts', 'duration')
    op.drop_column('processed_transcripts', 'channel_name')
    op.drop_column('processed_transcripts', 'video_title')
    op.drop_column('processed_transcripts', 'video_url')
    # ### end Alembic commands ###
