"""Add CEFR level fields to processed transcripts

Revision ID: 4129e9376817
Revises: a2d5ef5303a7
Create Date: 2025-08-06 11:22:16.442740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4129e9376817'
down_revision: Union[str, Sequence[str], None] = 'a2d5ef5303a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_transcripts', sa.Column('cefr_level', sa.String(length=5), nullable=True))
    op.add_column('processed_transcripts', sa.Column('level_confidence', sa.Integer(), nullable=True))
    op.add_column('processed_transcripts', sa.Column('level_analysis', sa.Text(), nullable=True))
    op.add_column('processed_transcripts', sa.Column('level_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_transcripts', 'level_analyzed_at')
    op.drop_column('processed_transcripts', 'level_analysis')
    op.drop_column('processed_transcripts', 'level_confidence')
    op.drop_column('processed_transcripts', 'cefr_level')
    # ### end Alembic commands ###
