"""Add CEFR level fields to transcript library

Revision ID: 6848985dde9c
Revises: c7933fa0658c
Create Date: 2025-08-06 11:14:18.392085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6848985dde9c'
down_revision: Union[str, Sequence[str], None] = 'c7933fa0658c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
