"""add_grammar_tracking_tables

Revision ID: b28ae545e024
Revises: 786ac0a7f51a
Create Date: 2025-07-31 19:18:06.457271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28ae545e024'
down_revision: Union[str, Sequence[str], None] = '786ac0a7f51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('pattern_key', sa.String(length=50), nullable=False),
    sa.Column('description_turkish', sa.Text(), nullable=False),
    sa.Column('description_english', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_key'),
    sa.UniqueConstraint('pattern_name')
    )
    op.create_index(op.f('ix_grammar_patterns_id'), 'grammar_patterns', ['id'], unique=False)
    op.create_table('user_grammar_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grammar_pattern', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_grammar_knowledge_id'), 'user_grammar_knowledge', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_grammar_knowledge_id'), table_name='user_grammar_knowledge')
    op.drop_table('user_grammar_knowledge')
    op.drop_index(op.f('ix_grammar_patterns_id'), table_name='grammar_patterns')
    op.drop_table('grammar_patterns')
    # ### end Alembic commands ###
