"""add_word_definitions_cache_table

Revision ID: c7933fa0658c
Revises: 391042c0cbc0
Create Date: 2025-08-03 16:00:14.421551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7933fa0658c'
down_revision: Union[str, Sequence[str], None] = '391042c0cbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('turkish_meaning', sa.Text(), nullable=True),
    sa.Column('english_example', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_definitions_id'), 'word_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_word_definitions_word'), 'word_definitions', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_definitions_word'), table_name='word_definitions')
    op.drop_index(op.f('ix_word_definitions_id'), table_name='word_definitions')
    op.drop_table('word_definitions')
    # ### end Alembic commands ###
