"""add_translation_and_learned_at_to_user_vocabulary

Revision ID: eeea4e4937d3
Revises: b28ae545e024
Create Date: 2025-07-31 20:09:04.774707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeea4e4937d3'
down_revision: Union[str, Sequence[str], None] = 'b28ae545e024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_vocabularies', sa.Column('translation', sa.Text(), nullable=True))
    op.add_column('user_vocabularies', sa.Column('learned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_vocabularies', 'learned_at')
    op.drop_column('user_vocabularies', 'translation')
    # ### end Alembic commands ###
