"""Add CEFR level fields to url content

Revision ID: f78fdd85a51e
Revises: 4129e9376817
Create Date: 2025-08-06 11:30:43.152127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78fdd85a51e'
down_revision: Union[str, Sequence[str], None] = '4129e9376817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_content', sa.Column('cefr_level', sa.String(length=5), nullable=True))
    op.add_column('url_content', sa.Column('level_confidence', sa.Integer(), nullable=True))
    op.add_column('url_content', sa.Column('level_analysis', sa.Text(), nullable=True))
    op.add_column('url_content', sa.Column('level_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_content', 'level_analyzed_at')
    op.drop_column('url_content', 'level_analysis')
    op.drop_column('url_content', 'level_confidence')
    op.drop_column('url_content', 'cefr_level')
    # ### end Alembic commands ###
