"""Add CEFR level fields to url content

Revision ID: f78fdd85a51e
Revises: 4129e9376817
Create Date: 2025-08-06 11:30:43.152127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78fdd85a51e'
down_revision: Union[str, Sequence[str], None] = '4129e9376817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_content', sa.Column('cefr_level', sa.String(length=5), nullable=True))
    op.add_column('url_content', sa.Column('level_confidence', sa.Integer(), nullable=True))
    op.add_column('url_content', sa.Column('level_analysis', sa.Text(), nullable=True))
    op.add_column('url_content', sa.Column('level_analyzed_at', sa.DateTime(timezone=True), nullable=True))

    # New fields for ownership and stats
    op.add_column('url_content', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('url_content', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'url_content', 'users', ['added_by_user_id'], ['id'])

    # Adjust unique constraint: drop old unique on url, add composite unique (url, added_by_user_id)
    try:
        op.drop_index('ix_url_content_url', table_name='url_content')
    except Exception:
        pass
    op.create_index('ix_url_content_url', 'url_content', ['url'], unique=False)
    op.create_unique_constraint('uq_urlcontent_url_user', 'url_content', ['url', 'added_by_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint('uq_urlcontent_url_user', 'url_content', type_='unique')
    except Exception:
        pass
    op.drop_constraint(None, 'url_content', type_='foreignkey')
    op.drop_column('url_content', 'added_by_user_id')
    op.drop_column('url_content', 'word_count')
    op.drop_column('url_content', 'level_analyzed_at')
    op.drop_column('url_content', 'level_analysis')
    op.drop_column('url_content', 'level_confidence')
    op.drop_column('url_content', 'cefr_level')
    # ### end Alembic commands ###
